apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vista-claim0
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      name: vista-pv-claim0
  resources:
    requests:
      storage: 100Mi
