apiVersion: v1
kind: PersistentVolume
metadata:
  name: vista-pv-claim0
  labels:
    name: vista-pv-claim0
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /kube/volumes/vista/claim0
