apiVersion: v1
kind: Service
metadata:
  labels:
    app: vista
  name: vista
spec:
  ports:
  - port: 2223
    protocol: TCP
    targetPort: 22
    name: ssh
  - port: 1338
    protocol: TCP
    targetPort: 1338
    name: rocto
  selector:
    app: vista
  sessionAffinity: None
